#!/usr/bin/env node
/**
 * key-local.js — generate js/secrets.js from your .env file for local dev.
 *
 * Usage:
 *   1. Copy .env.example to .env and put your rotated key in MAPTILER_KEY.
 *   2. Run: npm run key:local
 *   3. js/secrets.js is created (gitignored, never committed).
 *
 * Production/preview deploys do NOT use this file — they use
 * scripts/inject-key.js with the hosting provider's env vars.
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const ENV_PATH = path.join(ROOT, '.env');
const SECRETS_PATH = path.join(ROOT, 'js', 'secrets.js');

function loadEnv() {
  if (!fs.existsSync(ENV_PATH)) {
    console.error('[key:local] ERROR: .env not found. Copy .env.example to .env first.');
    process.exit(1);
  }
  const lines = fs.readFileSync(ENV_PATH, 'utf8').split('\n');
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    const k = trimmed.slice(0, eq).trim();
    const v = trimmed.slice(eq + 1).trim().replace(/^["']|["']$/g, '');
    if (k === 'MAPTILER_KEY') return v;
  }
  return '';
}

function main() {
  const key = loadEnv();
  if (!key || key === '__MAPTILER_KEY__') {
    console.error('[key:local] ERROR: MAPTILER_KEY in .env is missing or still the placeholder.');
    process.exit(1);
  }
  const content = `/**
 * secrets.js — LOCAL ONLY (gitignored, generated by npm run key:local).
 * DO NOT COMMIT. Production uses build-time injection (scripts/inject-key.js).
 */
window.__MAPTILER_KEY__ = '${key}';
`;
  fs.writeFileSync(SECRETS_PATH, content, 'utf8');
  console.log('[key:local] js/secrets.js generated from .env — local dev ready.');
}

main();
